with Gade.GB;
with Gade.Dev.CPU.Instructions.Arithmetic.Instances;
with Gade.Dev.CPU.Instructions.Loads.Instances;
with Gade.Dev.CPU.Instructions.Bitwise.Instances;
with Gade.Dev.CPU.Instructions.Logic.Instances;
with Gade.Dev.CPU.Instructions.Stack.Instances;
with Gade.Dev.CPU.Instructions.Flow.Instances;
with Gade.Dev.CPU.Instructions.Control;

package Gade.Dev.CPU.Exec is

   type Instruction_Handler is access procedure (GB : in out Gade.GB.GB_Type);

   procedure Execute
     (CPU    : in out CPU_Context;
      GB     : in out Gade.GB.GB_Type;
      Cycles : out M_Cycle_Count);

private
   package Arithmetic renames Gade.Dev.CPU.Instructions.Arithmetic.Instances;
   package Loads renames Gade.Dev.CPU.Instructions.Loads.Instances;
   package Bitwise renames Gade.Dev.CPU.Instructions.Bitwise.Instances;
   package Logic renames Gade.Dev.CPU.Instructions.Logic.Instances;
   package Stack renames Gade.Dev.CPU.Instructions.Stack.Instances;
   package Flow renames Gade.Dev.CPU.Instructions.Flow.Instances;
   package Control renames Gade.Dev.CPU.Instructions.Control;

   type Handler_Table is array (Byte) of Instruction_Handler;

   procedure Execute_Invalid_Main_Opcode
     (GB : in out Gade.GB.GB_Type);

   procedure Execute_Main_CB_Prefix
     (GB : in out Gade.GB.GB_Type);

   Main_Table : constant Handler_Table :=
     [
      16#00# => Control.Execute_NOP'Access,
      16#01# => Loads.Execute_LD_BC_Imm16'Access,
      16#02# => Loads.Execute_LD_Addr_BC_A'Access,
      16#03# => Arithmetic.Execute_INC_BC'Access,
      16#04# => Arithmetic.Execute_INC_B'Access,
      16#05# => Arithmetic.Execute_DEC_B'Access,
      16#06# => Loads.Execute_LD_B_Imm8'Access,
      16#07# => Bitwise.Execute_RLCA'Access,
      16#08# => Loads.Execute_LD_Addr_Imm16_SP'Access,
      16#09# => Arithmetic.Execute_ADD_HL_BC'Access,
      16#0A# => Loads.Execute_LD_A_Addr_BC'Access,
      16#0B# => Arithmetic.Execute_DEC_BC'Access,
      16#0C# => Arithmetic.Execute_INC_C'Access,
      16#0D# => Arithmetic.Execute_DEC_C'Access,
      16#0E# => Loads.Execute_LD_C_Imm8'Access,
      16#0F# => Bitwise.Execute_RRCA'Access,

      16#10# => Control.Execute_STOP'Access,
      16#11# => Loads.Execute_LD_DE_Imm16'Access,
      16#12# => Loads.Execute_LD_Addr_DE_A'Access,
      16#13# => Arithmetic.Execute_INC_DE'Access,
      16#14# => Arithmetic.Execute_INC_D'Access,
      16#15# => Arithmetic.Execute_DEC_D'Access,
      16#16# => Loads.Execute_LD_D_Imm8'Access,
      16#17# => Bitwise.Execute_RLA'Access,
      16#18# => Flow.Execute_JR'Access,
      16#19# => Arithmetic.Execute_ADD_HL_DE'Access,
      16#1A# => Loads.Execute_LD_A_Addr_DE'Access,
      16#1B# => Arithmetic.Execute_DEC_DE'Access,
      16#1C# => Arithmetic.Execute_INC_E'Access,
      16#1D# => Arithmetic.Execute_DEC_E'Access,
      16#1E# => Loads.Execute_LD_E_Imm8'Access,
      16#1F# => Bitwise.Execute_RRA'Access,

      16#20# => Flow.Execute_JR_NZ'Access,
      16#21# => Loads.Execute_LD_HL_Imm16'Access,
      16#22# => Loads.Execute_LD_Addr_HL_Inc_A'Access,
      16#23# => Arithmetic.Execute_INC_HL'Access,
      16#24# => Arithmetic.Execute_INC_H'Access,
      16#25# => Arithmetic.Execute_DEC_H'Access,
      16#26# => Loads.Execute_LD_H_Imm8'Access,
      16#27# => Arithmetic.Execute_DAA'Access,
      16#28# => Flow.Execute_JR_Z'Access,
      16#29# => Arithmetic.Execute_ADD_HL_HL'Access,
      16#2A# => Loads.Execute_LD_A_Addr_HL_Inc'Access,
      16#2B# => Arithmetic.Execute_DEC_HL'Access,
      16#2C# => Arithmetic.Execute_INC_L'Access,
      16#2D# => Arithmetic.Execute_DEC_L'Access,
      16#2E# => Loads.Execute_LD_L_Imm8'Access,
      16#2F# => Control.Execute_CPL'Access,

      16#30# => Flow.Execute_JR_NC'Access,
      16#31# => Loads.Execute_LD_SP_Imm16'Access,
      16#32# => Loads.Execute_LD_Addr_HL_Dec_A'Access,
      16#33# => Arithmetic.Execute_INC_SP'Access,
      16#34# => Arithmetic.Execute_INC_Addr_HL'Access,
      16#35# => Arithmetic.Execute_DEC_Addr_HL'Access,
      16#36# => Loads.Execute_LD_Addr_HL_Imm8'Access,
      16#37# => Control.Execute_SCF'Access,
      16#38# => Flow.Execute_JR_C'Access,
      16#39# => Arithmetic.Execute_ADD_HL_SP'Access,
      16#3A# => Loads.Execute_LD_A_Addr_HL_Dec'Access,
      16#3B# => Arithmetic.Execute_DEC_SP'Access,
      16#3C# => Arithmetic.Execute_INC_A'Access,
      16#3D# => Arithmetic.Execute_DEC_A'Access,
      16#3E# => Loads.Execute_LD_A_Imm8'Access,
      16#3F# => Control.Execute_CCF'Access,

      16#40# => Loads.Execute_LD_B_B'Access,
      16#41# => Loads.Execute_LD_B_C'Access,
      16#42# => Loads.Execute_LD_B_D'Access,
      16#43# => Loads.Execute_LD_B_E'Access,
      16#44# => Loads.Execute_LD_B_H'Access,
      16#45# => Loads.Execute_LD_B_L'Access,
      16#46# => Loads.Execute_LD_B_Addr_HL'Access,
      16#47# => Loads.Execute_LD_B_A'Access,
      16#48# => Loads.Execute_LD_C_B'Access,
      16#49# => Loads.Execute_LD_C_C'Access,
      16#4A# => Loads.Execute_LD_C_D'Access,
      16#4B# => Loads.Execute_LD_C_E'Access,
      16#4C# => Loads.Execute_LD_C_H'Access,
      16#4D# => Loads.Execute_LD_C_L'Access,
      16#4E# => Loads.Execute_LD_C_Addr_HL'Access,
      16#4F# => Loads.Execute_LD_C_A'Access,

      16#50# => Loads.Execute_LD_D_B'Access,
      16#51# => Loads.Execute_LD_D_C'Access,
      16#52# => Loads.Execute_LD_D_D'Access,
      16#53# => Loads.Execute_LD_D_E'Access,
      16#54# => Loads.Execute_LD_D_H'Access,
      16#55# => Loads.Execute_LD_D_L'Access,
      16#56# => Loads.Execute_LD_D_Addr_HL'Access,
      16#57# => Loads.Execute_LD_D_A'Access,
      16#58# => Loads.Execute_LD_E_B'Access,
      16#59# => Loads.Execute_LD_E_C'Access,
      16#5A# => Loads.Execute_LD_E_D'Access,
      16#5B# => Loads.Execute_LD_E_E'Access,
      16#5C# => Loads.Execute_LD_E_H'Access,
      16#5D# => Loads.Execute_LD_E_L'Access,
      16#5E# => Loads.Execute_LD_E_Addr_HL'Access,
      16#5F# => Loads.Execute_LD_E_A'Access,

      16#60# => Loads.Execute_LD_H_B'Access,
      16#61# => Loads.Execute_LD_H_C'Access,
      16#62# => Loads.Execute_LD_H_D'Access,
      16#63# => Loads.Execute_LD_H_E'Access,
      16#64# => Loads.Execute_LD_H_H'Access,
      16#65# => Loads.Execute_LD_H_L'Access,
      16#66# => Loads.Execute_LD_H_Addr_HL'Access,
      16#67# => Loads.Execute_LD_H_A'Access,
      16#68# => Loads.Execute_LD_L_B'Access,
      16#69# => Loads.Execute_LD_L_C'Access,
      16#6A# => Loads.Execute_LD_L_D'Access,
      16#6B# => Loads.Execute_LD_L_E'Access,
      16#6C# => Loads.Execute_LD_L_H'Access,
      16#6D# => Loads.Execute_LD_L_L'Access,
      16#6E# => Loads.Execute_LD_L_Addr_HL'Access,
      16#6F# => Loads.Execute_LD_L_A'Access,

      16#70# => Loads.Execute_LD_Addr_HL_B'Access,
      16#71# => Loads.Execute_LD_Addr_HL_C'Access,
      16#72# => Loads.Execute_LD_Addr_HL_D'Access,
      16#73# => Loads.Execute_LD_Addr_HL_E'Access,
      16#74# => Loads.Execute_LD_Addr_HL_H'Access,
      16#75# => Loads.Execute_LD_Addr_HL_L'Access,
      16#76# => Control.Execute_HALT'Access,
      16#77# => Loads.Execute_LD_Addr_HL_A'Access,
      16#78# => Loads.Execute_LD_A_B'Access,
      16#79# => Loads.Execute_LD_A_C'Access,
      16#7A# => Loads.Execute_LD_A_D'Access,
      16#7B# => Loads.Execute_LD_A_E'Access,
      16#7C# => Loads.Execute_LD_A_H'Access,
      16#7D# => Loads.Execute_LD_A_L'Access,
      16#7E# => Loads.Execute_LD_A_Addr_HL'Access,
      16#7F# => Loads.Execute_LD_A_A'Access,

      16#80# => Arithmetic.Execute_ADD_A_B'Access,
      16#81# => Arithmetic.Execute_ADD_A_C'Access,
      16#82# => Arithmetic.Execute_ADD_A_D'Access,
      16#83# => Arithmetic.Execute_ADD_A_E'Access,
      16#84# => Arithmetic.Execute_ADD_A_H'Access,
      16#85# => Arithmetic.Execute_ADD_A_L'Access,
      16#86# => Arithmetic.Execute_ADD_A_Addr_HL'Access,
      16#87# => Arithmetic.Execute_ADD_A_A'Access,
      16#88# => Arithmetic.Execute_ADC_A_B'Access,
      16#89# => Arithmetic.Execute_ADC_A_C'Access,
      16#8A# => Arithmetic.Execute_ADC_A_D'Access,
      16#8B# => Arithmetic.Execute_ADC_A_E'Access,
      16#8C# => Arithmetic.Execute_ADC_A_H'Access,
      16#8D# => Arithmetic.Execute_ADC_A_L'Access,
      16#8E# => Arithmetic.Execute_ADC_A_Addr_HL'Access,
      16#8F# => Arithmetic.Execute_ADC_A_A'Access,

      16#90# => Arithmetic.Execute_SUB_A_B'Access,
      16#91# => Arithmetic.Execute_SUB_A_C'Access,
      16#92# => Arithmetic.Execute_SUB_A_D'Access,
      16#93# => Arithmetic.Execute_SUB_A_E'Access,
      16#94# => Arithmetic.Execute_SUB_A_H'Access,
      16#95# => Arithmetic.Execute_SUB_A_L'Access,
      16#96# => Arithmetic.Execute_SUB_A_Addr_HL'Access,
      16#97# => Arithmetic.Execute_SUB_A_A'Access,
      16#98# => Arithmetic.Execute_SBC_A_B'Access,
      16#99# => Arithmetic.Execute_SBC_A_C'Access,
      16#9A# => Arithmetic.Execute_SBC_A_D'Access,
      16#9B# => Arithmetic.Execute_SBC_A_E'Access,
      16#9C# => Arithmetic.Execute_SBC_A_H'Access,
      16#9D# => Arithmetic.Execute_SBC_A_L'Access,
      16#9E# => Arithmetic.Execute_SBC_A_Addr_HL'Access,
      16#9F# => Arithmetic.Execute_SBC_A_A'Access,

      16#A0# => Logic.Execute_AND_A_B'Access,
      16#A1# => Logic.Execute_AND_A_C'Access,
      16#A2# => Logic.Execute_AND_A_D'Access,
      16#A3# => Logic.Execute_AND_A_E'Access,
      16#A4# => Logic.Execute_AND_A_H'Access,
      16#A5# => Logic.Execute_AND_A_L'Access,
      16#A6# => Logic.Execute_AND_A_Addr_HL'Access,
      16#A7# => Logic.Execute_AND_A_A'Access,
      16#A8# => Logic.Execute_XOR_A_B'Access,
      16#A9# => Logic.Execute_XOR_A_C'Access,
      16#AA# => Logic.Execute_XOR_A_D'Access,
      16#AB# => Logic.Execute_XOR_A_E'Access,
      16#AC# => Logic.Execute_XOR_A_H'Access,
      16#AD# => Logic.Execute_XOR_A_L'Access,
      16#AE# => Logic.Execute_XOR_A_Addr_HL'Access,
      16#AF# => Logic.Execute_XOR_A_A'Access,

      16#B0# => Logic.Execute_OR_A_B'Access,
      16#B1# => Logic.Execute_OR_A_C'Access,
      16#B2# => Logic.Execute_OR_A_D'Access,
      16#B3# => Logic.Execute_OR_A_E'Access,
      16#B4# => Logic.Execute_OR_A_H'Access,
      16#B5# => Logic.Execute_OR_A_L'Access,
      16#B6# => Logic.Execute_OR_A_Addr_HL'Access,
      16#B7# => Logic.Execute_OR_A_A'Access,
      16#B8# => Logic.Execute_CP_A_B'Access,
      16#B9# => Logic.Execute_CP_A_C'Access,
      16#BA# => Logic.Execute_CP_A_D'Access,
      16#BB# => Logic.Execute_CP_A_E'Access,
      16#BC# => Logic.Execute_CP_A_H'Access,
      16#BD# => Logic.Execute_CP_A_L'Access,
      16#BE# => Logic.Execute_CP_A_Addr_HL'Access,
      16#BF# => Logic.Execute_CP_A_A'Access,

      16#C0# => Flow.Execute_RET_NZ'Access,
      16#C1# => Stack.Execute_POP_BC'Access,
      16#C2# => Flow.Execute_JP_NZ'Access,
      16#C3# => Flow.Execute_JP'Access,
      16#C4# => Flow.Execute_CALL_NZ'Access,
      16#C5# => Stack.Execute_PUSH_BC'Access,
      16#C6# => Arithmetic.Execute_ADD_A_Imm8'Access,
      16#C7# => Flow.Execute_RST_00'Access,
      16#C8# => Flow.Execute_RET_Z'Access,
      16#C9# => Flow.Execute_RET'Access,
      16#CA# => Flow.Execute_JP_Z'Access,
      16#CB# => Execute_Main_CB_Prefix'Access,
      16#CC# => Flow.Execute_CALL_Z'Access,
      16#CD# => Flow.Execute_CALL'Access,
      16#CE# => Arithmetic.Execute_ADC_A_Imm8'Access,
      16#CF# => Flow.Execute_RST_08'Access,

      16#D0# => Flow.Execute_RET_NC'Access,
      16#D1# => Stack.Execute_POP_DE'Access,
      16#D2# => Flow.Execute_JP_NC'Access,
      16#D3# => Execute_Invalid_Main_Opcode'Access,
      16#D4# => Flow.Execute_CALL_NC'Access,
      16#D5# => Stack.Execute_PUSH_DE'Access,
      16#D6# => Arithmetic.Execute_SUB_A_Imm8'Access,
      16#D7# => Flow.Execute_RST_10'Access,
      16#D8# => Flow.Execute_RET_C'Access,
      16#D9# => Flow.Execute_RETI'Access,
      16#DA# => Flow.Execute_JP_C'Access,
      16#DB# => Execute_Invalid_Main_Opcode'Access,
      16#DC# => Flow.Execute_CALL_C'Access,
      16#DD# => Execute_Invalid_Main_Opcode'Access,
      16#DE# => Arithmetic.Execute_SBC_A_Imm8'Access,
      16#DF# => Flow.Execute_RST_18'Access,

      16#E0# => Loads.Execute_LD_High_Addr_Imm8_A'Access,
      16#E1# => Stack.Execute_POP_HL'Access,
      16#E2# => Loads.Execute_LD_High_Addr_C_A'Access,
      16#E3# => Execute_Invalid_Main_Opcode'Access,
      16#E4# => Execute_Invalid_Main_Opcode'Access,
      16#E5# => Stack.Execute_PUSH_HL'Access,
      16#E6# => Logic.Execute_AND_A_Imm8'Access,
      16#E7# => Flow.Execute_RST_20'Access,
      16#E8# => Arithmetic.Execute_ADD_SP_Imm8'Access,
      16#E9# => Flow.Execute_JP_HL'Access,
      16#EA# => Loads.Execute_LD_Addr_Imm16_A'Access,
      16#EB# => Execute_Invalid_Main_Opcode'Access,
      16#EC# => Execute_Invalid_Main_Opcode'Access,
      16#ED# => Execute_Invalid_Main_Opcode'Access,
      16#EE# => Logic.Execute_XOR_A_Imm8'Access,
      16#EF# => Flow.Execute_RST_28'Access,

      16#F0# => Loads.Execute_LD_A_High_Addr_Imm8'Access,
      16#F1# => Stack.Execute_POP_AF'Access,
      16#F2# => Loads.Execute_LD_A_High_Addr_C'Access,
      16#F3# => Control.Execute_DI'Access,
      16#F4# => Execute_Invalid_Main_Opcode'Access,
      16#F5# => Stack.Execute_PUSH_AF'Access,
      16#F6# => Logic.Execute_OR_A_Imm8'Access,
      16#F7# => Flow.Execute_RST_30'Access,
      16#F8# => Loads.Execute_LD_HL_SP_Plus_Imm8'Access,
      16#F9# => Loads.Execute_LD_SP_HL'Access,
      16#FA# => Loads.Execute_LD_A_Addr_Imm16'Access,
      16#FB# => Control.Execute_EI'Access,
      16#FC# => Execute_Invalid_Main_Opcode'Access,
      16#FD# => Execute_Invalid_Main_Opcode'Access,
      16#FE# => Logic.Execute_CP_A_Imm8'Access,
      16#FF# => Flow.Execute_RST_38'Access
     ];

   CB_Table : constant Handler_Table :=
     [
      16#00# => Bitwise.Execute_RLC_B'Access,
      16#01# => Bitwise.Execute_RLC_C'Access,
      16#02# => Bitwise.Execute_RLC_D'Access,
      16#03# => Bitwise.Execute_RLC_E'Access,
      16#04# => Bitwise.Execute_RLC_H'Access,
      16#05# => Bitwise.Execute_RLC_L'Access,
      16#06# => Bitwise.Execute_RLC_Addr_HL'Access,
      16#07# => Bitwise.Execute_RLC_A'Access,
      16#08# => Bitwise.Execute_RRC_B'Access,
      16#09# => Bitwise.Execute_RRC_C'Access,
      16#0A# => Bitwise.Execute_RRC_D'Access,
      16#0B# => Bitwise.Execute_RRC_E'Access,
      16#0C# => Bitwise.Execute_RRC_H'Access,
      16#0D# => Bitwise.Execute_RRC_L'Access,
      16#0E# => Bitwise.Execute_RRC_Addr_HL'Access,
      16#0F# => Bitwise.Execute_RRC_A'Access,

      16#10# => Bitwise.Execute_RL_B'Access,
      16#11# => Bitwise.Execute_RL_C'Access,
      16#12# => Bitwise.Execute_RL_D'Access,
      16#13# => Bitwise.Execute_RL_E'Access,
      16#14# => Bitwise.Execute_RL_H'Access,
      16#15# => Bitwise.Execute_RL_L'Access,
      16#16# => Bitwise.Execute_RL_Addr_HL'Access,
      16#17# => Bitwise.Execute_RL_A'Access,
      16#18# => Bitwise.Execute_RR_B'Access,
      16#19# => Bitwise.Execute_RR_C'Access,
      16#1A# => Bitwise.Execute_RR_D'Access,
      16#1B# => Bitwise.Execute_RR_E'Access,
      16#1C# => Bitwise.Execute_RR_H'Access,
      16#1D# => Bitwise.Execute_RR_L'Access,
      16#1E# => Bitwise.Execute_RR_Addr_HL'Access,
      16#1F# => Bitwise.Execute_RR_A'Access,

      16#20# => Bitwise.Execute_SLA_B'Access,
      16#21# => Bitwise.Execute_SLA_C'Access,
      16#22# => Bitwise.Execute_SLA_D'Access,
      16#23# => Bitwise.Execute_SLA_E'Access,
      16#24# => Bitwise.Execute_SLA_H'Access,
      16#25# => Bitwise.Execute_SLA_L'Access,
      16#26# => Bitwise.Execute_SLA_Addr_HL'Access,
      16#27# => Bitwise.Execute_SLA_A'Access,
      16#28# => Bitwise.Execute_SRA_B'Access,
      16#29# => Bitwise.Execute_SRA_C'Access,
      16#2A# => Bitwise.Execute_SRA_D'Access,
      16#2B# => Bitwise.Execute_SRA_E'Access,
      16#2C# => Bitwise.Execute_SRA_H'Access,
      16#2D# => Bitwise.Execute_SRA_L'Access,
      16#2E# => Bitwise.Execute_SRA_Addr_HL'Access,
      16#2F# => Bitwise.Execute_SRA_A'Access,

      16#30# => Bitwise.Execute_SWAP_B'Access,
      16#31# => Bitwise.Execute_SWAP_C'Access,
      16#32# => Bitwise.Execute_SWAP_D'Access,
      16#33# => Bitwise.Execute_SWAP_E'Access,
      16#34# => Bitwise.Execute_SWAP_H'Access,
      16#35# => Bitwise.Execute_SWAP_L'Access,
      16#36# => Bitwise.Execute_SWAP_Addr_HL'Access,
      16#37# => Bitwise.Execute_SWAP_A'Access,
      16#38# => Bitwise.Execute_SRL_B'Access,
      16#39# => Bitwise.Execute_SRL_C'Access,
      16#3A# => Bitwise.Execute_SRL_D'Access,
      16#3B# => Bitwise.Execute_SRL_E'Access,
      16#3C# => Bitwise.Execute_SRL_H'Access,
      16#3D# => Bitwise.Execute_SRL_L'Access,
      16#3E# => Bitwise.Execute_SRL_Addr_HL'Access,
      16#3F# => Bitwise.Execute_SRL_A'Access,

      16#40# => Bitwise.Execute_BIT_0_B'Access,
      16#41# => Bitwise.Execute_BIT_0_C'Access,
      16#42# => Bitwise.Execute_BIT_0_D'Access,
      16#43# => Bitwise.Execute_BIT_0_E'Access,
      16#44# => Bitwise.Execute_BIT_0_H'Access,
      16#45# => Bitwise.Execute_BIT_0_L'Access,
      16#46# => Bitwise.Execute_BIT_0_Addr_HL'Access,
      16#47# => Bitwise.Execute_BIT_0_A'Access,
      16#48# => Bitwise.Execute_BIT_1_B'Access,
      16#49# => Bitwise.Execute_BIT_1_C'Access,
      16#4A# => Bitwise.Execute_BIT_1_D'Access,
      16#4B# => Bitwise.Execute_BIT_1_E'Access,
      16#4C# => Bitwise.Execute_BIT_1_H'Access,
      16#4D# => Bitwise.Execute_BIT_1_L'Access,
      16#4E# => Bitwise.Execute_BIT_1_Addr_HL'Access,
      16#4F# => Bitwise.Execute_BIT_1_A'Access,

      16#50# => Bitwise.Execute_BIT_2_B'Access,
      16#51# => Bitwise.Execute_BIT_2_C'Access,
      16#52# => Bitwise.Execute_BIT_2_D'Access,
      16#53# => Bitwise.Execute_BIT_2_E'Access,
      16#54# => Bitwise.Execute_BIT_2_H'Access,
      16#55# => Bitwise.Execute_BIT_2_L'Access,
      16#56# => Bitwise.Execute_BIT_2_Addr_HL'Access,
      16#57# => Bitwise.Execute_BIT_2_A'Access,
      16#58# => Bitwise.Execute_BIT_3_B'Access,
      16#59# => Bitwise.Execute_BIT_3_C'Access,
      16#5A# => Bitwise.Execute_BIT_3_D'Access,
      16#5B# => Bitwise.Execute_BIT_3_E'Access,
      16#5C# => Bitwise.Execute_BIT_3_H'Access,
      16#5D# => Bitwise.Execute_BIT_3_L'Access,
      16#5E# => Bitwise.Execute_BIT_3_Addr_HL'Access,
      16#5F# => Bitwise.Execute_BIT_3_A'Access,

      16#60# => Bitwise.Execute_BIT_4_B'Access,
      16#61# => Bitwise.Execute_BIT_4_C'Access,
      16#62# => Bitwise.Execute_BIT_4_D'Access,
      16#63# => Bitwise.Execute_BIT_4_E'Access,
      16#64# => Bitwise.Execute_BIT_4_H'Access,
      16#65# => Bitwise.Execute_BIT_4_L'Access,
      16#66# => Bitwise.Execute_BIT_4_Addr_HL'Access,
      16#67# => Bitwise.Execute_BIT_4_A'Access,
      16#68# => Bitwise.Execute_BIT_5_B'Access,
      16#69# => Bitwise.Execute_BIT_5_C'Access,
      16#6A# => Bitwise.Execute_BIT_5_D'Access,
      16#6B# => Bitwise.Execute_BIT_5_E'Access,
      16#6C# => Bitwise.Execute_BIT_5_H'Access,
      16#6D# => Bitwise.Execute_BIT_5_L'Access,
      16#6E# => Bitwise.Execute_BIT_5_Addr_HL'Access,
      16#6F# => Bitwise.Execute_BIT_5_A'Access,

      16#70# => Bitwise.Execute_BIT_6_B'Access,
      16#71# => Bitwise.Execute_BIT_6_C'Access,
      16#72# => Bitwise.Execute_BIT_6_D'Access,
      16#73# => Bitwise.Execute_BIT_6_E'Access,
      16#74# => Bitwise.Execute_BIT_6_H'Access,
      16#75# => Bitwise.Execute_BIT_6_L'Access,
      16#76# => Bitwise.Execute_BIT_6_Addr_HL'Access,
      16#77# => Bitwise.Execute_BIT_6_A'Access,
      16#78# => Bitwise.Execute_BIT_7_B'Access,
      16#79# => Bitwise.Execute_BIT_7_C'Access,
      16#7A# => Bitwise.Execute_BIT_7_D'Access,
      16#7B# => Bitwise.Execute_BIT_7_E'Access,
      16#7C# => Bitwise.Execute_BIT_7_H'Access,
      16#7D# => Bitwise.Execute_BIT_7_L'Access,
      16#7E# => Bitwise.Execute_BIT_7_Addr_HL'Access,
      16#7F# => Bitwise.Execute_BIT_7_A'Access,

      16#80# => Bitwise.Execute_RES_0_B'Access,
      16#81# => Bitwise.Execute_RES_0_C'Access,
      16#82# => Bitwise.Execute_RES_0_D'Access,
      16#83# => Bitwise.Execute_RES_0_E'Access,
      16#84# => Bitwise.Execute_RES_0_H'Access,
      16#85# => Bitwise.Execute_RES_0_L'Access,
      16#86# => Bitwise.Execute_RES_0_Addr_HL'Access,
      16#87# => Bitwise.Execute_RES_0_A'Access,
      16#88# => Bitwise.Execute_RES_1_B'Access,
      16#89# => Bitwise.Execute_RES_1_C'Access,
      16#8A# => Bitwise.Execute_RES_1_D'Access,
      16#8B# => Bitwise.Execute_RES_1_E'Access,
      16#8C# => Bitwise.Execute_RES_1_H'Access,
      16#8D# => Bitwise.Execute_RES_1_L'Access,
      16#8E# => Bitwise.Execute_RES_1_Addr_HL'Access,
      16#8F# => Bitwise.Execute_RES_1_A'Access,

      16#90# => Bitwise.Execute_RES_2_B'Access,
      16#91# => Bitwise.Execute_RES_2_C'Access,
      16#92# => Bitwise.Execute_RES_2_D'Access,
      16#93# => Bitwise.Execute_RES_2_E'Access,
      16#94# => Bitwise.Execute_RES_2_H'Access,
      16#95# => Bitwise.Execute_RES_2_L'Access,
      16#96# => Bitwise.Execute_RES_2_Addr_HL'Access,
      16#97# => Bitwise.Execute_RES_2_A'Access,
      16#98# => Bitwise.Execute_RES_3_B'Access,
      16#99# => Bitwise.Execute_RES_3_C'Access,
      16#9A# => Bitwise.Execute_RES_3_D'Access,
      16#9B# => Bitwise.Execute_RES_3_E'Access,
      16#9C# => Bitwise.Execute_RES_3_H'Access,
      16#9D# => Bitwise.Execute_RES_3_L'Access,
      16#9E# => Bitwise.Execute_RES_3_Addr_HL'Access,
      16#9F# => Bitwise.Execute_RES_3_A'Access,

      16#A0# => Bitwise.Execute_RES_4_B'Access,
      16#A1# => Bitwise.Execute_RES_4_C'Access,
      16#A2# => Bitwise.Execute_RES_4_D'Access,
      16#A3# => Bitwise.Execute_RES_4_E'Access,
      16#A4# => Bitwise.Execute_RES_4_H'Access,
      16#A5# => Bitwise.Execute_RES_4_L'Access,
      16#A6# => Bitwise.Execute_RES_4_Addr_HL'Access,
      16#A7# => Bitwise.Execute_RES_4_A'Access,
      16#A8# => Bitwise.Execute_RES_5_B'Access,
      16#A9# => Bitwise.Execute_RES_5_C'Access,
      16#AA# => Bitwise.Execute_RES_5_D'Access,
      16#AB# => Bitwise.Execute_RES_5_E'Access,
      16#AC# => Bitwise.Execute_RES_5_H'Access,
      16#AD# => Bitwise.Execute_RES_5_L'Access,
      16#AE# => Bitwise.Execute_RES_5_Addr_HL'Access,
      16#AF# => Bitwise.Execute_RES_5_A'Access,

      16#B0# => Bitwise.Execute_RES_6_B'Access,
      16#B1# => Bitwise.Execute_RES_6_C'Access,
      16#B2# => Bitwise.Execute_RES_6_D'Access,
      16#B3# => Bitwise.Execute_RES_6_E'Access,
      16#B4# => Bitwise.Execute_RES_6_H'Access,
      16#B5# => Bitwise.Execute_RES_6_L'Access,
      16#B6# => Bitwise.Execute_RES_6_Addr_HL'Access,
      16#B7# => Bitwise.Execute_RES_6_A'Access,
      16#B8# => Bitwise.Execute_RES_7_B'Access,
      16#B9# => Bitwise.Execute_RES_7_C'Access,
      16#BA# => Bitwise.Execute_RES_7_D'Access,
      16#BB# => Bitwise.Execute_RES_7_E'Access,
      16#BC# => Bitwise.Execute_RES_7_H'Access,
      16#BD# => Bitwise.Execute_RES_7_L'Access,
      16#BE# => Bitwise.Execute_RES_7_Addr_HL'Access,
      16#BF# => Bitwise.Execute_RES_7_A'Access,

      16#C0# => Bitwise.Execute_SET_0_B'Access,
      16#C1# => Bitwise.Execute_SET_0_C'Access,
      16#C2# => Bitwise.Execute_SET_0_D'Access,
      16#C3# => Bitwise.Execute_SET_0_E'Access,
      16#C4# => Bitwise.Execute_SET_0_H'Access,
      16#C5# => Bitwise.Execute_SET_0_L'Access,
      16#C6# => Bitwise.Execute_SET_0_Addr_HL'Access,
      16#C7# => Bitwise.Execute_SET_0_A'Access,
      16#C8# => Bitwise.Execute_SET_1_B'Access,
      16#C9# => Bitwise.Execute_SET_1_C'Access,
      16#CA# => Bitwise.Execute_SET_1_D'Access,
      16#CB# => Bitwise.Execute_SET_1_E'Access,
      16#CC# => Bitwise.Execute_SET_1_H'Access,
      16#CD# => Bitwise.Execute_SET_1_L'Access,
      16#CE# => Bitwise.Execute_SET_1_Addr_HL'Access,
      16#CF# => Bitwise.Execute_SET_1_A'Access,

      16#D0# => Bitwise.Execute_SET_2_B'Access,
      16#D1# => Bitwise.Execute_SET_2_C'Access,
      16#D2# => Bitwise.Execute_SET_2_D'Access,
      16#D3# => Bitwise.Execute_SET_2_E'Access,
      16#D4# => Bitwise.Execute_SET_2_H'Access,
      16#D5# => Bitwise.Execute_SET_2_L'Access,
      16#D6# => Bitwise.Execute_SET_2_Addr_HL'Access,
      16#D7# => Bitwise.Execute_SET_2_A'Access,
      16#D8# => Bitwise.Execute_SET_3_B'Access,
      16#D9# => Bitwise.Execute_SET_3_C'Access,
      16#DA# => Bitwise.Execute_SET_3_D'Access,
      16#DB# => Bitwise.Execute_SET_3_E'Access,
      16#DC# => Bitwise.Execute_SET_3_H'Access,
      16#DD# => Bitwise.Execute_SET_3_L'Access,
      16#DE# => Bitwise.Execute_SET_3_Addr_HL'Access,
      16#DF# => Bitwise.Execute_SET_3_A'Access,

      16#E0# => Bitwise.Execute_SET_4_B'Access,
      16#E1# => Bitwise.Execute_SET_4_C'Access,
      16#E2# => Bitwise.Execute_SET_4_D'Access,
      16#E3# => Bitwise.Execute_SET_4_E'Access,
      16#E4# => Bitwise.Execute_SET_4_H'Access,
      16#E5# => Bitwise.Execute_SET_4_L'Access,
      16#E6# => Bitwise.Execute_SET_4_Addr_HL'Access,
      16#E7# => Bitwise.Execute_SET_4_A'Access,
      16#E8# => Bitwise.Execute_SET_5_B'Access,
      16#E9# => Bitwise.Execute_SET_5_C'Access,
      16#EA# => Bitwise.Execute_SET_5_D'Access,
      16#EB# => Bitwise.Execute_SET_5_E'Access,
      16#EC# => Bitwise.Execute_SET_5_H'Access,
      16#ED# => Bitwise.Execute_SET_5_L'Access,
      16#EE# => Bitwise.Execute_SET_5_Addr_HL'Access,
      16#EF# => Bitwise.Execute_SET_5_A'Access,

      16#F0# => Bitwise.Execute_SET_6_B'Access,
      16#F1# => Bitwise.Execute_SET_6_C'Access,
      16#F2# => Bitwise.Execute_SET_6_D'Access,
      16#F3# => Bitwise.Execute_SET_6_E'Access,
      16#F4# => Bitwise.Execute_SET_6_H'Access,
      16#F5# => Bitwise.Execute_SET_6_L'Access,
      16#F6# => Bitwise.Execute_SET_6_Addr_HL'Access,
      16#F7# => Bitwise.Execute_SET_6_A'Access,
      16#F8# => Bitwise.Execute_SET_7_B'Access,
      16#F9# => Bitwise.Execute_SET_7_C'Access,
      16#FA# => Bitwise.Execute_SET_7_D'Access,
      16#FB# => Bitwise.Execute_SET_7_E'Access,
      16#FC# => Bitwise.Execute_SET_7_H'Access,
      16#FD# => Bitwise.Execute_SET_7_L'Access,
      16#FE# => Bitwise.Execute_SET_7_Addr_HL'Access,
      16#FF# => Bitwise.Execute_SET_7_A'Access
     ];

end Gade.Dev.CPU.Exec;
