with Gade.GB;
with Gade.Dev.CPU.Instructions.Arithmetic.Instances;
with Gade.Dev.CPU.Instructions.Loads.Instances;
with Gade.Dev.CPU.Instructions.Bitwise.Instances;
with Gade.Dev.CPU.Instructions.Logic.Instances;
with Gade.Dev.CPU.Instructions.Stack.Instances;
with Gade.Dev.CPU.Instructions.Flow.Instances;
with Gade.Dev.CPU.Instructions.Control.Instances;

package Gade.Dev.CPU.Exec is

   type Instruction_Handler is access procedure (GB : in out Gade.GB.GB_Type);

   procedure Execute
     (CPU    : in out CPU_Context;
      GB     : in out Gade.GB.GB_Type;
      Cycles : out M_Cycle_Count);

private
   package Arithmetic renames Gade.Dev.CPU.Instructions.Arithmetic.Instances;
   package Loads renames Gade.Dev.CPU.Instructions.Loads.Instances;
   package Bitwise renames Gade.Dev.CPU.Instructions.Bitwise.Instances;
   package Logic renames Gade.Dev.CPU.Instructions.Logic.Instances;
   package Stack renames Gade.Dev.CPU.Instructions.Stack.Instances;
   package Flow renames Gade.Dev.CPU.Instructions.Flow.Instances;
   package Control renames Gade.Dev.CPU.Instructions.Control.Instances;

   type Handler_Table is array (Byte) of Instruction_Handler;

   procedure Invalid_Main_Opcode
     (GB : in out Gade.GB.GB_Type);

   procedure Main_CB_Prefix
     (GB : in out Gade.GB.GB_Type);

   Main_Table : constant Handler_Table :=
     [
      16#00# => Control.NOP'Access,
      16#01# => Loads.LD_BC_Imm16'Access,
      16#02# => Loads.LD_Addr_BC_A'Access,
      16#03# => Arithmetic.INC_BC'Access,
      16#04# => Arithmetic.INC_B'Access,
      16#05# => Arithmetic.DEC_B'Access,
      16#06# => Loads.LD_B_Imm8'Access,
      16#07# => Bitwise.RLCA'Access,
      16#08# => Loads.LD_Addr_Imm16_SP'Access,
      16#09# => Arithmetic.ADD_HL_BC'Access,
      16#0A# => Loads.LD_A_Addr_BC'Access,
      16#0B# => Arithmetic.DEC_BC'Access,
      16#0C# => Arithmetic.INC_C'Access,
      16#0D# => Arithmetic.DEC_C'Access,
      16#0E# => Loads.LD_C_Imm8'Access,
      16#0F# => Bitwise.RRCA'Access,

      16#10# => Control.STOP'Access,
      16#11# => Loads.LD_DE_Imm16'Access,
      16#12# => Loads.LD_Addr_DE_A'Access,
      16#13# => Arithmetic.INC_DE'Access,
      16#14# => Arithmetic.INC_D'Access,
      16#15# => Arithmetic.DEC_D'Access,
      16#16# => Loads.LD_D_Imm8'Access,
      16#17# => Bitwise.RLA'Access,
      16#18# => Flow.JR'Access,
      16#19# => Arithmetic.ADD_HL_DE'Access,
      16#1A# => Loads.LD_A_Addr_DE'Access,
      16#1B# => Arithmetic.DEC_DE'Access,
      16#1C# => Arithmetic.INC_E'Access,
      16#1D# => Arithmetic.DEC_E'Access,
      16#1E# => Loads.LD_E_Imm8'Access,
      16#1F# => Bitwise.RRA'Access,

      16#20# => Flow.JR_NZ'Access,
      16#21# => Loads.LD_HL_Imm16'Access,
      16#22# => Loads.LD_Addr_HL_Inc_A'Access,
      16#23# => Arithmetic.INC_HL'Access,
      16#24# => Arithmetic.INC_H'Access,
      16#25# => Arithmetic.DEC_H'Access,
      16#26# => Loads.LD_H_Imm8'Access,
      16#27# => Arithmetic.DAA'Access,
      16#28# => Flow.JR_Z'Access,
      16#29# => Arithmetic.ADD_HL_HL'Access,
      16#2A# => Loads.LD_A_Addr_HL_Inc'Access,
      16#2B# => Arithmetic.DEC_HL'Access,
      16#2C# => Arithmetic.INC_L'Access,
      16#2D# => Arithmetic.DEC_L'Access,
      16#2E# => Loads.LD_L_Imm8'Access,
      16#2F# => Control.CPL'Access,

      16#30# => Flow.JR_NC'Access,
      16#31# => Loads.LD_SP_Imm16'Access,
      16#32# => Loads.LD_Addr_HL_Dec_A'Access,
      16#33# => Arithmetic.INC_SP'Access,
      16#34# => Arithmetic.INC_Addr_HL'Access,
      16#35# => Arithmetic.DEC_Addr_HL'Access,
      16#36# => Loads.LD_Addr_HL_Imm8'Access,
      16#37# => Control.SCF'Access,
      16#38# => Flow.JR_C'Access,
      16#39# => Arithmetic.ADD_HL_SP'Access,
      16#3A# => Loads.LD_A_Addr_HL_Dec'Access,
      16#3B# => Arithmetic.DEC_SP'Access,
      16#3C# => Arithmetic.INC_A'Access,
      16#3D# => Arithmetic.DEC_A'Access,
      16#3E# => Loads.LD_A_Imm8'Access,
      16#3F# => Control.CCF'Access,

      16#40# => Loads.LD_B_B'Access,
      16#41# => Loads.LD_B_C'Access,
      16#42# => Loads.LD_B_D'Access,
      16#43# => Loads.LD_B_E'Access,
      16#44# => Loads.LD_B_H'Access,
      16#45# => Loads.LD_B_L'Access,
      16#46# => Loads.LD_B_Addr_HL'Access,
      16#47# => Loads.LD_B_A'Access,
      16#48# => Loads.LD_C_B'Access,
      16#49# => Loads.LD_C_C'Access,
      16#4A# => Loads.LD_C_D'Access,
      16#4B# => Loads.LD_C_E'Access,
      16#4C# => Loads.LD_C_H'Access,
      16#4D# => Loads.LD_C_L'Access,
      16#4E# => Loads.LD_C_Addr_HL'Access,
      16#4F# => Loads.LD_C_A'Access,

      16#50# => Loads.LD_D_B'Access,
      16#51# => Loads.LD_D_C'Access,
      16#52# => Loads.LD_D_D'Access,
      16#53# => Loads.LD_D_E'Access,
      16#54# => Loads.LD_D_H'Access,
      16#55# => Loads.LD_D_L'Access,
      16#56# => Loads.LD_D_Addr_HL'Access,
      16#57# => Loads.LD_D_A'Access,
      16#58# => Loads.LD_E_B'Access,
      16#59# => Loads.LD_E_C'Access,
      16#5A# => Loads.LD_E_D'Access,
      16#5B# => Loads.LD_E_E'Access,
      16#5C# => Loads.LD_E_H'Access,
      16#5D# => Loads.LD_E_L'Access,
      16#5E# => Loads.LD_E_Addr_HL'Access,
      16#5F# => Loads.LD_E_A'Access,

      16#60# => Loads.LD_H_B'Access,
      16#61# => Loads.LD_H_C'Access,
      16#62# => Loads.LD_H_D'Access,
      16#63# => Loads.LD_H_E'Access,
      16#64# => Loads.LD_H_H'Access,
      16#65# => Loads.LD_H_L'Access,
      16#66# => Loads.LD_H_Addr_HL'Access,
      16#67# => Loads.LD_H_A'Access,
      16#68# => Loads.LD_L_B'Access,
      16#69# => Loads.LD_L_C'Access,
      16#6A# => Loads.LD_L_D'Access,
      16#6B# => Loads.LD_L_E'Access,
      16#6C# => Loads.LD_L_H'Access,
      16#6D# => Loads.LD_L_L'Access,
      16#6E# => Loads.LD_L_Addr_HL'Access,
      16#6F# => Loads.LD_L_A'Access,

      16#70# => Loads.LD_Addr_HL_B'Access,
      16#71# => Loads.LD_Addr_HL_C'Access,
      16#72# => Loads.LD_Addr_HL_D'Access,
      16#73# => Loads.LD_Addr_HL_E'Access,
      16#74# => Loads.LD_Addr_HL_H'Access,
      16#75# => Loads.LD_Addr_HL_L'Access,
      16#76# => Control.HALT'Access,
      16#77# => Loads.LD_Addr_HL_A'Access,
      16#78# => Loads.LD_A_B'Access,
      16#79# => Loads.LD_A_C'Access,
      16#7A# => Loads.LD_A_D'Access,
      16#7B# => Loads.LD_A_E'Access,
      16#7C# => Loads.LD_A_H'Access,
      16#7D# => Loads.LD_A_L'Access,
      16#7E# => Loads.LD_A_Addr_HL'Access,
      16#7F# => Loads.LD_A_A'Access,

      16#80# => Arithmetic.ADD_A_B'Access,
      16#81# => Arithmetic.ADD_A_C'Access,
      16#82# => Arithmetic.ADD_A_D'Access,
      16#83# => Arithmetic.ADD_A_E'Access,
      16#84# => Arithmetic.ADD_A_H'Access,
      16#85# => Arithmetic.ADD_A_L'Access,
      16#86# => Arithmetic.ADD_A_Addr_HL'Access,
      16#87# => Arithmetic.ADD_A_A'Access,
      16#88# => Arithmetic.ADC_A_B'Access,
      16#89# => Arithmetic.ADC_A_C'Access,
      16#8A# => Arithmetic.ADC_A_D'Access,
      16#8B# => Arithmetic.ADC_A_E'Access,
      16#8C# => Arithmetic.ADC_A_H'Access,
      16#8D# => Arithmetic.ADC_A_L'Access,
      16#8E# => Arithmetic.ADC_A_Addr_HL'Access,
      16#8F# => Arithmetic.ADC_A_A'Access,

      16#90# => Arithmetic.SUB_A_B'Access,
      16#91# => Arithmetic.SUB_A_C'Access,
      16#92# => Arithmetic.SUB_A_D'Access,
      16#93# => Arithmetic.SUB_A_E'Access,
      16#94# => Arithmetic.SUB_A_H'Access,
      16#95# => Arithmetic.SUB_A_L'Access,
      16#96# => Arithmetic.SUB_A_Addr_HL'Access,
      16#97# => Arithmetic.SUB_A_A'Access,
      16#98# => Arithmetic.SBC_A_B'Access,
      16#99# => Arithmetic.SBC_A_C'Access,
      16#9A# => Arithmetic.SBC_A_D'Access,
      16#9B# => Arithmetic.SBC_A_E'Access,
      16#9C# => Arithmetic.SBC_A_H'Access,
      16#9D# => Arithmetic.SBC_A_L'Access,
      16#9E# => Arithmetic.SBC_A_Addr_HL'Access,
      16#9F# => Arithmetic.SBC_A_A'Access,

      16#A0# => Logic.AND_A_B'Access,
      16#A1# => Logic.AND_A_C'Access,
      16#A2# => Logic.AND_A_D'Access,
      16#A3# => Logic.AND_A_E'Access,
      16#A4# => Logic.AND_A_H'Access,
      16#A5# => Logic.AND_A_L'Access,
      16#A6# => Logic.AND_A_Addr_HL'Access,
      16#A7# => Logic.AND_A_A'Access,
      16#A8# => Logic.XOR_A_B'Access,
      16#A9# => Logic.XOR_A_C'Access,
      16#AA# => Logic.XOR_A_D'Access,
      16#AB# => Logic.XOR_A_E'Access,
      16#AC# => Logic.XOR_A_H'Access,
      16#AD# => Logic.XOR_A_L'Access,
      16#AE# => Logic.XOR_A_Addr_HL'Access,
      16#AF# => Logic.XOR_A_A'Access,

      16#B0# => Logic.OR_A_B'Access,
      16#B1# => Logic.OR_A_C'Access,
      16#B2# => Logic.OR_A_D'Access,
      16#B3# => Logic.OR_A_E'Access,
      16#B4# => Logic.OR_A_H'Access,
      16#B5# => Logic.OR_A_L'Access,
      16#B6# => Logic.OR_A_Addr_HL'Access,
      16#B7# => Logic.OR_A_A'Access,
      16#B8# => Logic.CP_A_B'Access,
      16#B9# => Logic.CP_A_C'Access,
      16#BA# => Logic.CP_A_D'Access,
      16#BB# => Logic.CP_A_E'Access,
      16#BC# => Logic.CP_A_H'Access,
      16#BD# => Logic.CP_A_L'Access,
      16#BE# => Logic.CP_A_Addr_HL'Access,
      16#BF# => Logic.CP_A_A'Access,

      16#C0# => Flow.RET_NZ'Access,
      16#C1# => Stack.POP_BC'Access,
      16#C2# => Flow.JP_NZ'Access,
      16#C3# => Flow.JP'Access,
      16#C4# => Flow.CALL_NZ'Access,
      16#C5# => Stack.PUSH_BC'Access,
      16#C6# => Arithmetic.ADD_A_Imm8'Access,
      16#C7# => Flow.RST_00'Access,
      16#C8# => Flow.RET_Z'Access,
      16#C9# => Flow.RET'Access,
      16#CA# => Flow.JP_Z'Access,
      16#CB# => Main_CB_Prefix'Access,
      16#CC# => Flow.CALL_Z'Access,
      16#CD# => Flow.CALL'Access,
      16#CE# => Arithmetic.ADC_A_Imm8'Access,
      16#CF# => Flow.RST_08'Access,

      16#D0# => Flow.RET_NC'Access,
      16#D1# => Stack.POP_DE'Access,
      16#D2# => Flow.JP_NC'Access,
      16#D3# => Invalid_Main_Opcode'Access,
      16#D4# => Flow.CALL_NC'Access,
      16#D5# => Stack.PUSH_DE'Access,
      16#D6# => Arithmetic.SUB_A_Imm8'Access,
      16#D7# => Flow.RST_10'Access,
      16#D8# => Flow.RET_C'Access,
      16#D9# => Flow.RETI'Access,
      16#DA# => Flow.JP_C'Access,
      16#DB# => Invalid_Main_Opcode'Access,
      16#DC# => Flow.CALL_C'Access,
      16#DD# => Invalid_Main_Opcode'Access,
      16#DE# => Arithmetic.SBC_A_Imm8'Access,
      16#DF# => Flow.RST_18'Access,

      16#E0# => Loads.LD_High_Addr_Imm8_A'Access,
      16#E1# => Stack.POP_HL'Access,
      16#E2# => Loads.LD_High_Addr_C_A'Access,
      16#E3# => Invalid_Main_Opcode'Access,
      16#E4# => Invalid_Main_Opcode'Access,
      16#E5# => Stack.PUSH_HL'Access,
      16#E6# => Logic.AND_A_Imm8'Access,
      16#E7# => Flow.RST_20'Access,
      16#E8# => Arithmetic.ADD_SP_Imm8'Access,
      16#E9# => Flow.JP_HL'Access,
      16#EA# => Loads.LD_Addr_Imm16_A'Access,
      16#EB# => Invalid_Main_Opcode'Access,
      16#EC# => Invalid_Main_Opcode'Access,
      16#ED# => Invalid_Main_Opcode'Access,
      16#EE# => Logic.XOR_A_Imm8'Access,
      16#EF# => Flow.RST_28'Access,

      16#F0# => Loads.LD_A_High_Addr_Imm8'Access,
      16#F1# => Stack.POP_AF'Access,
      16#F2# => Loads.LD_A_High_Addr_C'Access,
      16#F3# => Control.DI'Access,
      16#F4# => Invalid_Main_Opcode'Access,
      16#F5# => Stack.PUSH_AF'Access,
      16#F6# => Logic.OR_A_Imm8'Access,
      16#F7# => Flow.RST_30'Access,
      16#F8# => Loads.LD_HL_SP_Plus_Imm8'Access,
      16#F9# => Loads.LD_SP_HL'Access,
      16#FA# => Loads.LD_A_Addr_Imm16'Access,
      16#FB# => Control.EI'Access,
      16#FC# => Invalid_Main_Opcode'Access,
      16#FD# => Invalid_Main_Opcode'Access,
      16#FE# => Logic.CP_A_Imm8'Access,
      16#FF# => Flow.RST_38'Access
     ];

   CB_Table : constant Handler_Table :=
     [
      16#00# => Bitwise.RLC_B'Access,
      16#01# => Bitwise.RLC_C'Access,
      16#02# => Bitwise.RLC_D'Access,
      16#03# => Bitwise.RLC_E'Access,
      16#04# => Bitwise.RLC_H'Access,
      16#05# => Bitwise.RLC_L'Access,
      16#06# => Bitwise.RLC_Addr_HL'Access,
      16#07# => Bitwise.RLC_A'Access,
      16#08# => Bitwise.RRC_B'Access,
      16#09# => Bitwise.RRC_C'Access,
      16#0A# => Bitwise.RRC_D'Access,
      16#0B# => Bitwise.RRC_E'Access,
      16#0C# => Bitwise.RRC_H'Access,
      16#0D# => Bitwise.RRC_L'Access,
      16#0E# => Bitwise.RRC_Addr_HL'Access,
      16#0F# => Bitwise.RRC_A'Access,

      16#10# => Bitwise.RL_B'Access,
      16#11# => Bitwise.RL_C'Access,
      16#12# => Bitwise.RL_D'Access,
      16#13# => Bitwise.RL_E'Access,
      16#14# => Bitwise.RL_H'Access,
      16#15# => Bitwise.RL_L'Access,
      16#16# => Bitwise.RL_Addr_HL'Access,
      16#17# => Bitwise.RL_A'Access,
      16#18# => Bitwise.RR_B'Access,
      16#19# => Bitwise.RR_C'Access,
      16#1A# => Bitwise.RR_D'Access,
      16#1B# => Bitwise.RR_E'Access,
      16#1C# => Bitwise.RR_H'Access,
      16#1D# => Bitwise.RR_L'Access,
      16#1E# => Bitwise.RR_Addr_HL'Access,
      16#1F# => Bitwise.RR_A'Access,

      16#20# => Bitwise.SLA_B'Access,
      16#21# => Bitwise.SLA_C'Access,
      16#22# => Bitwise.SLA_D'Access,
      16#23# => Bitwise.SLA_E'Access,
      16#24# => Bitwise.SLA_H'Access,
      16#25# => Bitwise.SLA_L'Access,
      16#26# => Bitwise.SLA_Addr_HL'Access,
      16#27# => Bitwise.SLA_A'Access,
      16#28# => Bitwise.SRA_B'Access,
      16#29# => Bitwise.SRA_C'Access,
      16#2A# => Bitwise.SRA_D'Access,
      16#2B# => Bitwise.SRA_E'Access,
      16#2C# => Bitwise.SRA_H'Access,
      16#2D# => Bitwise.SRA_L'Access,
      16#2E# => Bitwise.SRA_Addr_HL'Access,
      16#2F# => Bitwise.SRA_A'Access,

      16#30# => Bitwise.SWAP_B'Access,
      16#31# => Bitwise.SWAP_C'Access,
      16#32# => Bitwise.SWAP_D'Access,
      16#33# => Bitwise.SWAP_E'Access,
      16#34# => Bitwise.SWAP_H'Access,
      16#35# => Bitwise.SWAP_L'Access,
      16#36# => Bitwise.SWAP_Addr_HL'Access,
      16#37# => Bitwise.SWAP_A'Access,
      16#38# => Bitwise.SRL_B'Access,
      16#39# => Bitwise.SRL_C'Access,
      16#3A# => Bitwise.SRL_D'Access,
      16#3B# => Bitwise.SRL_E'Access,
      16#3C# => Bitwise.SRL_H'Access,
      16#3D# => Bitwise.SRL_L'Access,
      16#3E# => Bitwise.SRL_Addr_HL'Access,
      16#3F# => Bitwise.SRL_A'Access,

      16#40# => Bitwise.BIT_0_B'Access,
      16#41# => Bitwise.BIT_0_C'Access,
      16#42# => Bitwise.BIT_0_D'Access,
      16#43# => Bitwise.BIT_0_E'Access,
      16#44# => Bitwise.BIT_0_H'Access,
      16#45# => Bitwise.BIT_0_L'Access,
      16#46# => Bitwise.BIT_0_Addr_HL'Access,
      16#47# => Bitwise.BIT_0_A'Access,
      16#48# => Bitwise.BIT_1_B'Access,
      16#49# => Bitwise.BIT_1_C'Access,
      16#4A# => Bitwise.BIT_1_D'Access,
      16#4B# => Bitwise.BIT_1_E'Access,
      16#4C# => Bitwise.BIT_1_H'Access,
      16#4D# => Bitwise.BIT_1_L'Access,
      16#4E# => Bitwise.BIT_1_Addr_HL'Access,
      16#4F# => Bitwise.BIT_1_A'Access,

      16#50# => Bitwise.BIT_2_B'Access,
      16#51# => Bitwise.BIT_2_C'Access,
      16#52# => Bitwise.BIT_2_D'Access,
      16#53# => Bitwise.BIT_2_E'Access,
      16#54# => Bitwise.BIT_2_H'Access,
      16#55# => Bitwise.BIT_2_L'Access,
      16#56# => Bitwise.BIT_2_Addr_HL'Access,
      16#57# => Bitwise.BIT_2_A'Access,
      16#58# => Bitwise.BIT_3_B'Access,
      16#59# => Bitwise.BIT_3_C'Access,
      16#5A# => Bitwise.BIT_3_D'Access,
      16#5B# => Bitwise.BIT_3_E'Access,
      16#5C# => Bitwise.BIT_3_H'Access,
      16#5D# => Bitwise.BIT_3_L'Access,
      16#5E# => Bitwise.BIT_3_Addr_HL'Access,
      16#5F# => Bitwise.BIT_3_A'Access,

      16#60# => Bitwise.BIT_4_B'Access,
      16#61# => Bitwise.BIT_4_C'Access,
      16#62# => Bitwise.BIT_4_D'Access,
      16#63# => Bitwise.BIT_4_E'Access,
      16#64# => Bitwise.BIT_4_H'Access,
      16#65# => Bitwise.BIT_4_L'Access,
      16#66# => Bitwise.BIT_4_Addr_HL'Access,
      16#67# => Bitwise.BIT_4_A'Access,
      16#68# => Bitwise.BIT_5_B'Access,
      16#69# => Bitwise.BIT_5_C'Access,
      16#6A# => Bitwise.BIT_5_D'Access,
      16#6B# => Bitwise.BIT_5_E'Access,
      16#6C# => Bitwise.BIT_5_H'Access,
      16#6D# => Bitwise.BIT_5_L'Access,
      16#6E# => Bitwise.BIT_5_Addr_HL'Access,
      16#6F# => Bitwise.BIT_5_A'Access,

      16#70# => Bitwise.BIT_6_B'Access,
      16#71# => Bitwise.BIT_6_C'Access,
      16#72# => Bitwise.BIT_6_D'Access,
      16#73# => Bitwise.BIT_6_E'Access,
      16#74# => Bitwise.BIT_6_H'Access,
      16#75# => Bitwise.BIT_6_L'Access,
      16#76# => Bitwise.BIT_6_Addr_HL'Access,
      16#77# => Bitwise.BIT_6_A'Access,
      16#78# => Bitwise.BIT_7_B'Access,
      16#79# => Bitwise.BIT_7_C'Access,
      16#7A# => Bitwise.BIT_7_D'Access,
      16#7B# => Bitwise.BIT_7_E'Access,
      16#7C# => Bitwise.BIT_7_H'Access,
      16#7D# => Bitwise.BIT_7_L'Access,
      16#7E# => Bitwise.BIT_7_Addr_HL'Access,
      16#7F# => Bitwise.BIT_7_A'Access,

      16#80# => Bitwise.RES_0_B'Access,
      16#81# => Bitwise.RES_0_C'Access,
      16#82# => Bitwise.RES_0_D'Access,
      16#83# => Bitwise.RES_0_E'Access,
      16#84# => Bitwise.RES_0_H'Access,
      16#85# => Bitwise.RES_0_L'Access,
      16#86# => Bitwise.RES_0_Addr_HL'Access,
      16#87# => Bitwise.RES_0_A'Access,
      16#88# => Bitwise.RES_1_B'Access,
      16#89# => Bitwise.RES_1_C'Access,
      16#8A# => Bitwise.RES_1_D'Access,
      16#8B# => Bitwise.RES_1_E'Access,
      16#8C# => Bitwise.RES_1_H'Access,
      16#8D# => Bitwise.RES_1_L'Access,
      16#8E# => Bitwise.RES_1_Addr_HL'Access,
      16#8F# => Bitwise.RES_1_A'Access,

      16#90# => Bitwise.RES_2_B'Access,
      16#91# => Bitwise.RES_2_C'Access,
      16#92# => Bitwise.RES_2_D'Access,
      16#93# => Bitwise.RES_2_E'Access,
      16#94# => Bitwise.RES_2_H'Access,
      16#95# => Bitwise.RES_2_L'Access,
      16#96# => Bitwise.RES_2_Addr_HL'Access,
      16#97# => Bitwise.RES_2_A'Access,
      16#98# => Bitwise.RES_3_B'Access,
      16#99# => Bitwise.RES_3_C'Access,
      16#9A# => Bitwise.RES_3_D'Access,
      16#9B# => Bitwise.RES_3_E'Access,
      16#9C# => Bitwise.RES_3_H'Access,
      16#9D# => Bitwise.RES_3_L'Access,
      16#9E# => Bitwise.RES_3_Addr_HL'Access,
      16#9F# => Bitwise.RES_3_A'Access,

      16#A0# => Bitwise.RES_4_B'Access,
      16#A1# => Bitwise.RES_4_C'Access,
      16#A2# => Bitwise.RES_4_D'Access,
      16#A3# => Bitwise.RES_4_E'Access,
      16#A4# => Bitwise.RES_4_H'Access,
      16#A5# => Bitwise.RES_4_L'Access,
      16#A6# => Bitwise.RES_4_Addr_HL'Access,
      16#A7# => Bitwise.RES_4_A'Access,
      16#A8# => Bitwise.RES_5_B'Access,
      16#A9# => Bitwise.RES_5_C'Access,
      16#AA# => Bitwise.RES_5_D'Access,
      16#AB# => Bitwise.RES_5_E'Access,
      16#AC# => Bitwise.RES_5_H'Access,
      16#AD# => Bitwise.RES_5_L'Access,
      16#AE# => Bitwise.RES_5_Addr_HL'Access,
      16#AF# => Bitwise.RES_5_A'Access,

      16#B0# => Bitwise.RES_6_B'Access,
      16#B1# => Bitwise.RES_6_C'Access,
      16#B2# => Bitwise.RES_6_D'Access,
      16#B3# => Bitwise.RES_6_E'Access,
      16#B4# => Bitwise.RES_6_H'Access,
      16#B5# => Bitwise.RES_6_L'Access,
      16#B6# => Bitwise.RES_6_Addr_HL'Access,
      16#B7# => Bitwise.RES_6_A'Access,
      16#B8# => Bitwise.RES_7_B'Access,
      16#B9# => Bitwise.RES_7_C'Access,
      16#BA# => Bitwise.RES_7_D'Access,
      16#BB# => Bitwise.RES_7_E'Access,
      16#BC# => Bitwise.RES_7_H'Access,
      16#BD# => Bitwise.RES_7_L'Access,
      16#BE# => Bitwise.RES_7_Addr_HL'Access,
      16#BF# => Bitwise.RES_7_A'Access,

      16#C0# => Bitwise.SET_0_B'Access,
      16#C1# => Bitwise.SET_0_C'Access,
      16#C2# => Bitwise.SET_0_D'Access,
      16#C3# => Bitwise.SET_0_E'Access,
      16#C4# => Bitwise.SET_0_H'Access,
      16#C5# => Bitwise.SET_0_L'Access,
      16#C6# => Bitwise.SET_0_Addr_HL'Access,
      16#C7# => Bitwise.SET_0_A'Access,
      16#C8# => Bitwise.SET_1_B'Access,
      16#C9# => Bitwise.SET_1_C'Access,
      16#CA# => Bitwise.SET_1_D'Access,
      16#CB# => Bitwise.SET_1_E'Access,
      16#CC# => Bitwise.SET_1_H'Access,
      16#CD# => Bitwise.SET_1_L'Access,
      16#CE# => Bitwise.SET_1_Addr_HL'Access,
      16#CF# => Bitwise.SET_1_A'Access,

      16#D0# => Bitwise.SET_2_B'Access,
      16#D1# => Bitwise.SET_2_C'Access,
      16#D2# => Bitwise.SET_2_D'Access,
      16#D3# => Bitwise.SET_2_E'Access,
      16#D4# => Bitwise.SET_2_H'Access,
      16#D5# => Bitwise.SET_2_L'Access,
      16#D6# => Bitwise.SET_2_Addr_HL'Access,
      16#D7# => Bitwise.SET_2_A'Access,
      16#D8# => Bitwise.SET_3_B'Access,
      16#D9# => Bitwise.SET_3_C'Access,
      16#DA# => Bitwise.SET_3_D'Access,
      16#DB# => Bitwise.SET_3_E'Access,
      16#DC# => Bitwise.SET_3_H'Access,
      16#DD# => Bitwise.SET_3_L'Access,
      16#DE# => Bitwise.SET_3_Addr_HL'Access,
      16#DF# => Bitwise.SET_3_A'Access,

      16#E0# => Bitwise.SET_4_B'Access,
      16#E1# => Bitwise.SET_4_C'Access,
      16#E2# => Bitwise.SET_4_D'Access,
      16#E3# => Bitwise.SET_4_E'Access,
      16#E4# => Bitwise.SET_4_H'Access,
      16#E5# => Bitwise.SET_4_L'Access,
      16#E6# => Bitwise.SET_4_Addr_HL'Access,
      16#E7# => Bitwise.SET_4_A'Access,
      16#E8# => Bitwise.SET_5_B'Access,
      16#E9# => Bitwise.SET_5_C'Access,
      16#EA# => Bitwise.SET_5_D'Access,
      16#EB# => Bitwise.SET_5_E'Access,
      16#EC# => Bitwise.SET_5_H'Access,
      16#ED# => Bitwise.SET_5_L'Access,
      16#EE# => Bitwise.SET_5_Addr_HL'Access,
      16#EF# => Bitwise.SET_5_A'Access,

      16#F0# => Bitwise.SET_6_B'Access,
      16#F1# => Bitwise.SET_6_C'Access,
      16#F2# => Bitwise.SET_6_D'Access,
      16#F3# => Bitwise.SET_6_E'Access,
      16#F4# => Bitwise.SET_6_H'Access,
      16#F5# => Bitwise.SET_6_L'Access,
      16#F6# => Bitwise.SET_6_Addr_HL'Access,
      16#F7# => Bitwise.SET_6_A'Access,
      16#F8# => Bitwise.SET_7_B'Access,
      16#F9# => Bitwise.SET_7_C'Access,
      16#FA# => Bitwise.SET_7_D'Access,
      16#FB# => Bitwise.SET_7_E'Access,
      16#FC# => Bitwise.SET_7_H'Access,
      16#FD# => Bitwise.SET_7_L'Access,
      16#FE# => Bitwise.SET_7_Addr_HL'Access,
      16#FF# => Bitwise.SET_7_A'Access
     ];

end Gade.Dev.CPU.Exec;
