repos:
  - repo: local
    hooks:
      - id: gade-ada-format
        name: Format staged Ada files
        entry: sh ./scripts/check-ada-format-staged.sh
        language: system
        files: ".*\\.ad(b|s)$"
