# We are using Python 2.7 to run the testsuite
language: python
python:
  - "2.7"

# Global variables
env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - GNAT_BIN_PATH=$TOOLS_DIR/gnat-community-2019-x86_64-linux-bin

os:
  - linux

# Cache directory that allows us to not download GNAT GPL every time, speeding
# up the process.
cache:
  directories:
  - $HOME/build_tools

# Handle git submodules ourselves
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  # Check if the GNAT package is already available in the cache directory. If
  # not, download it.
  - test -f $GNAT_BIN_PATH ||( mkdir -p $TOOLS_DIR &&  wget http://mirrors.cdn.adacore.com/art/5cdffc5409dcd015aaf82626 -O $GNAT_BIN_PATH)

  # Download installation scripts
  - wget https://raw.githubusercontent.com/AdaCore/gnat_community_install_script/master/install_package.sh
  - wget https://raw.githubusercontent.com/AdaCore/gnat_community_install_script/master/install_script.qs

  # Install GNAT from its package
  - test -d $TOOLS_DIR/native/ ||( sh install_package.sh $GNAT_BIN_PATH $TOOLS_DIR/native/)

  # Add GNAT to $PATH
  - export PATH=$PATH:$TOOLS_DIR/native/bin/

script:
  # Show GNAT version for the record
  - $TOOLS_DIR/native/bin/gprbuild --version

  # Start the testsuite
  - python $PWD/testsuite/run.py
