with Gade.Dev.CPU.Generic_Instruction_Definitions;

package body Gade.Dev.CPU.Generic_Dispatch_Prototype is
   package Definitions renames Gade.Dev.CPU.Generic_Instruction_Definitions;

   type Handler_Table is array (Byte) of Instruction_Handler;

   function Build_Main_Table return Handler_Table;

   function Build_CB_Table return Handler_Table;

   function Build_Main_Table return Handler_Table is
      Table : Handler_Table := [others => null];
   begin
      Table (16#80#) := Definitions.Execute_ADD_A_B'Access;
      Table (16#86#) := Definitions.Execute_ADD_A_Addr_HL'Access;
      Table (16#89#) := Definitions.Execute_ADC_A_C'Access;
      Table (16#92#) := Definitions.Execute_SUB_A_D'Access;
      Table (16#9B#) := Definitions.Execute_SBC_A_E'Access;
      Table (16#A4#) := Definitions.Execute_AND_A_H'Access;
      Table (16#AD#) := Definitions.Execute_XOR_A_L'Access;
      Table (16#B7#) := Definitions.Execute_OR_A_A'Access;
      Table (16#BE#) := Definitions.Execute_CP_A_Addr_HL'Access;
      Table (16#01#) := Definitions.Execute_LD_BC_Imm16'Access;
      Table (16#02#) := Definitions.Execute_LD_Addr_BC_A'Access;
      Table (16#06#) := Definitions.Execute_LD_B_Imm8'Access;
      Table (16#08#) := Definitions.Execute_LD_Addr_Imm16_SP'Access;
      Table (16#0A#) := Definitions.Execute_LD_A_Addr_BC'Access;
      Table (16#0E#) := Definitions.Execute_LD_C_Imm8'Access;
      Table (16#11#) := Definitions.Execute_LD_DE_Imm16'Access;
      Table (16#12#) := Definitions.Execute_LD_Addr_DE_A'Access;
      Table (16#16#) := Definitions.Execute_LD_D_Imm8'Access;
      Table (16#1A#) := Definitions.Execute_LD_A_Addr_DE'Access;
      Table (16#1E#) := Definitions.Execute_LD_E_Imm8'Access;
      Table (16#21#) := Definitions.Execute_LD_HL_Imm16'Access;
      Table (16#22#) := Definitions.Execute_LD_Addr_HL_Inc_A'Access;
      Table (16#26#) := Definitions.Execute_LD_H_Imm8'Access;
      Table (16#2A#) := Definitions.Execute_LD_A_Addr_HL_Inc'Access;
      Table (16#2E#) := Definitions.Execute_LD_L_Imm8'Access;
      Table (16#31#) := Definitions.Execute_LD_SP_Imm16'Access;
      Table (16#32#) := Definitions.Execute_LD_Addr_HL_Dec_A'Access;
      Table (16#36#) := Definitions.Execute_LD_Addr_HL_Imm8'Access;
      Table (16#3A#) := Definitions.Execute_LD_A_Addr_HL_Dec'Access;
      Table (16#3E#) := Definitions.Execute_LD_A_Imm8'Access;
      Table (16#40#) := Definitions.Execute_LD_B_B'Access;
      Table (16#41#) := Definitions.Execute_LD_B_C'Access;
      Table (16#42#) := Definitions.Execute_LD_B_D'Access;
      Table (16#43#) := Definitions.Execute_LD_B_E'Access;
      Table (16#44#) := Definitions.Execute_LD_B_H'Access;
      Table (16#45#) := Definitions.Execute_LD_B_L'Access;
      Table (16#46#) := Definitions.Execute_LD_B_Addr_HL'Access;
      Table (16#47#) := Definitions.Execute_LD_B_A'Access;
      Table (16#48#) := Definitions.Execute_LD_C_B'Access;
      Table (16#49#) := Definitions.Execute_LD_C_C'Access;
      Table (16#4A#) := Definitions.Execute_LD_C_D'Access;
      Table (16#4B#) := Definitions.Execute_LD_C_E'Access;
      Table (16#4C#) := Definitions.Execute_LD_C_H'Access;
      Table (16#4D#) := Definitions.Execute_LD_C_L'Access;
      Table (16#4E#) := Definitions.Execute_LD_C_Addr_HL'Access;
      Table (16#4F#) := Definitions.Execute_LD_C_A'Access;
      Table (16#50#) := Definitions.Execute_LD_D_B'Access;
      Table (16#51#) := Definitions.Execute_LD_D_C'Access;
      Table (16#52#) := Definitions.Execute_LD_D_D'Access;
      Table (16#53#) := Definitions.Execute_LD_D_E'Access;
      Table (16#54#) := Definitions.Execute_LD_D_H'Access;
      Table (16#55#) := Definitions.Execute_LD_D_L'Access;
      Table (16#56#) := Definitions.Execute_LD_D_Addr_HL'Access;
      Table (16#57#) := Definitions.Execute_LD_D_A'Access;
      Table (16#58#) := Definitions.Execute_LD_E_B'Access;
      Table (16#59#) := Definitions.Execute_LD_E_C'Access;
      Table (16#5A#) := Definitions.Execute_LD_E_D'Access;
      Table (16#5B#) := Definitions.Execute_LD_E_E'Access;
      Table (16#5C#) := Definitions.Execute_LD_E_H'Access;
      Table (16#5D#) := Definitions.Execute_LD_E_L'Access;
      Table (16#5E#) := Definitions.Execute_LD_E_Addr_HL'Access;
      Table (16#5F#) := Definitions.Execute_LD_E_A'Access;
      Table (16#60#) := Definitions.Execute_LD_H_B'Access;
      Table (16#61#) := Definitions.Execute_LD_H_C'Access;
      Table (16#62#) := Definitions.Execute_LD_H_D'Access;
      Table (16#63#) := Definitions.Execute_LD_H_E'Access;
      Table (16#64#) := Definitions.Execute_LD_H_H'Access;
      Table (16#65#) := Definitions.Execute_LD_H_L'Access;
      Table (16#66#) := Definitions.Execute_LD_H_Addr_HL'Access;
      Table (16#67#) := Definitions.Execute_LD_H_A'Access;
      Table (16#68#) := Definitions.Execute_LD_L_B'Access;
      Table (16#69#) := Definitions.Execute_LD_L_C'Access;
      Table (16#6A#) := Definitions.Execute_LD_L_D'Access;
      Table (16#6B#) := Definitions.Execute_LD_L_E'Access;
      Table (16#6C#) := Definitions.Execute_LD_L_H'Access;
      Table (16#6D#) := Definitions.Execute_LD_L_L'Access;
      Table (16#6E#) := Definitions.Execute_LD_L_Addr_HL'Access;
      Table (16#6F#) := Definitions.Execute_LD_L_A'Access;
      Table (16#70#) := Definitions.Execute_LD_Addr_HL_B'Access;
      Table (16#71#) := Definitions.Execute_LD_Addr_HL_C'Access;
      Table (16#72#) := Definitions.Execute_LD_Addr_HL_D'Access;
      Table (16#73#) := Definitions.Execute_LD_Addr_HL_E'Access;
      Table (16#74#) := Definitions.Execute_LD_Addr_HL_H'Access;
      Table (16#75#) := Definitions.Execute_LD_Addr_HL_L'Access;
      Table (16#77#) := Definitions.Execute_LD_Addr_HL_A'Access;
      Table (16#78#) := Definitions.Execute_LD_A_B'Access;
      Table (16#79#) := Definitions.Execute_LD_A_C'Access;
      Table (16#7A#) := Definitions.Execute_LD_A_D'Access;
      Table (16#7B#) := Definitions.Execute_LD_A_E'Access;
      Table (16#7C#) := Definitions.Execute_LD_A_H'Access;
      Table (16#7D#) := Definitions.Execute_LD_A_L'Access;
      Table (16#7E#) := Definitions.Execute_LD_A_Addr_HL'Access;
      Table (16#7F#) := Definitions.Execute_LD_A_A'Access;
      Table (16#3E#) := Definitions.Execute_LD_A_Imm8'Access;
      Table (16#36#) := Definitions.Execute_LD_Addr_HL_Imm8'Access;
      Table (16#03#) := Definitions.Execute_INC_BC'Access;
      Table (16#04#) := Definitions.Execute_INC_B'Access;
      Table (16#05#) := Definitions.Execute_DEC_B'Access;
      Table (16#0B#) := Definitions.Execute_DEC_BC'Access;
      Table (16#0C#) := Definitions.Execute_INC_C'Access;
      Table (16#0D#) := Definitions.Execute_DEC_C'Access;
      Table (16#13#) := Definitions.Execute_INC_DE'Access;
      Table (16#14#) := Definitions.Execute_INC_D'Access;
      Table (16#15#) := Definitions.Execute_DEC_D'Access;
      Table (16#1B#) := Definitions.Execute_DEC_DE'Access;
      Table (16#1C#) := Definitions.Execute_INC_E'Access;
      Table (16#1D#) := Definitions.Execute_DEC_E'Access;
      Table (16#35#) := Definitions.Execute_DEC_Addr_HL'Access;
      Table (16#23#) := Definitions.Execute_INC_HL'Access;
      Table (16#24#) := Definitions.Execute_INC_H'Access;
      Table (16#25#) := Definitions.Execute_DEC_H'Access;
      Table (16#2B#) := Definitions.Execute_DEC_HL'Access;
      Table (16#2C#) := Definitions.Execute_INC_L'Access;
      Table (16#2D#) := Definitions.Execute_DEC_L'Access;
      Table (16#33#) := Definitions.Execute_INC_SP'Access;
      Table (16#34#) := Definitions.Execute_INC_Addr_HL'Access;
      Table (16#3B#) := Definitions.Execute_DEC_SP'Access;
      Table (16#3C#) := Definitions.Execute_INC_A'Access;
      Table (16#3D#) := Definitions.Execute_DEC_A'Access;
      Table (16#07#) := Definitions.Execute_RLCA'Access;
      Table (16#0F#) := Definitions.Execute_RRCA'Access;
      Table (16#17#) := Definitions.Execute_RLA'Access;
      Table (16#1F#) := Definitions.Execute_RRA'Access;
      Table (16#C1#) := Definitions.Execute_POP_BC'Access;
      Table (16#C5#) := Definitions.Execute_PUSH_BC'Access;
      Table (16#D1#) := Definitions.Execute_POP_DE'Access;
      Table (16#D5#) := Definitions.Execute_PUSH_DE'Access;
      Table (16#E1#) := Definitions.Execute_POP_HL'Access;
      Table (16#E5#) := Definitions.Execute_PUSH_HL'Access;
      Table (16#F1#) := Definitions.Execute_POP_AF'Access;
      Table (16#F5#) := Definitions.Execute_PUSH_AF'Access;
      Table (16#18#) := Definitions.Execute_JR'Access;
      Table (16#20#) := Definitions.Execute_JR_NZ'Access;
      Table (16#28#) := Definitions.Execute_JR_Z'Access;
      Table (16#30#) := Definitions.Execute_JR_NC'Access;
      Table (16#38#) := Definitions.Execute_JR_C'Access;
      Table (16#C2#) := Definitions.Execute_JP_NZ'Access;
      Table (16#C3#) := Definitions.Execute_JP'Access;
      Table (16#CA#) := Definitions.Execute_JP_Z'Access;
      Table (16#D2#) := Definitions.Execute_JP_NC'Access;
      Table (16#DA#) := Definitions.Execute_JP_C'Access;
      Table (16#E9#) := Definitions.Execute_JP_HL'Access;
      Table (16#C4#) := Definitions.Execute_CALL_NZ'Access;
      Table (16#CD#) := Definitions.Execute_CALL'Access;
      Table (16#CC#) := Definitions.Execute_CALL_Z'Access;
      Table (16#D4#) := Definitions.Execute_CALL_NC'Access;
      Table (16#DC#) := Definitions.Execute_CALL_C'Access;
      Table (16#C0#) := Definitions.Execute_RET_NZ'Access;
      Table (16#C8#) := Definitions.Execute_RET_Z'Access;
      Table (16#C9#) := Definitions.Execute_RET'Access;
      Table (16#D0#) := Definitions.Execute_RET_NC'Access;
      Table (16#D8#) := Definitions.Execute_RET_C'Access;
      Table (16#D9#) := Definitions.Execute_RETI'Access;
      Table (16#C7#) := Definitions.Execute_RST_00'Access;
      Table (16#CF#) := Definitions.Execute_RST_08'Access;
      Table (16#D7#) := Definitions.Execute_RST_10'Access;
      Table (16#DF#) := Definitions.Execute_RST_18'Access;
      Table (16#E7#) := Definitions.Execute_RST_20'Access;
      Table (16#EF#) := Definitions.Execute_RST_28'Access;
      Table (16#F7#) := Definitions.Execute_RST_30'Access;
      Table (16#FF#) := Definitions.Execute_RST_38'Access;
      Table (16#E0#) := Definitions.Execute_LD_High_Addr_Imm8_A'Access;
      Table (16#E2#) := Definitions.Execute_LD_High_Addr_C_A'Access;
      Table (16#EA#) := Definitions.Execute_LD_Addr_Imm16_A'Access;
      Table (16#F0#) := Definitions.Execute_LD_A_High_Addr_Imm8'Access;
      Table (16#F2#) := Definitions.Execute_LD_A_High_Addr_C'Access;
      Table (16#F8#) := Definitions.Execute_LD_HL_SP_Plus_Imm8'Access;
      Table (16#F9#) := Definitions.Execute_LD_SP_HL'Access;
      Table (16#FA#) := Definitions.Execute_LD_A_Addr_Imm16'Access;
      return Table;
   end Build_Main_Table;

   function Build_CB_Table return Handler_Table is
      Table : Handler_Table := [others => null];
   begin
      Table (16#40#) := Definitions.Execute_BIT_0_B'Access;
      Table (16#5E#) := Definitions.Execute_BIT_3_Addr_HL'Access;
      Table (16#A9#) := Definitions.Execute_RES_5_C'Access;
      Table (16#BE#) := Definitions.Execute_RES_7_Addr_HL'Access;
      Table (16#D7#) := Definitions.Execute_SET_2_A'Access;
      Table (16#F6#) := Definitions.Execute_SET_6_Addr_HL'Access;
      Table (16#00#) := Definitions.Execute_RLC_B'Access;
      Table (16#01#) := Definitions.Execute_RLC_C'Access;
      Table (16#02#) := Definitions.Execute_RLC_D'Access;
      Table (16#03#) := Definitions.Execute_RLC_E'Access;
      Table (16#04#) := Definitions.Execute_RLC_H'Access;
      Table (16#05#) := Definitions.Execute_RLC_L'Access;
      Table (16#06#) := Definitions.Execute_RLC_Addr_HL'Access;
      Table (16#07#) := Definitions.Execute_RLC_A'Access;
      Table (16#08#) := Definitions.Execute_RRC_B'Access;
      Table (16#09#) := Definitions.Execute_RRC_C'Access;
      Table (16#0A#) := Definitions.Execute_RRC_D'Access;
      Table (16#0B#) := Definitions.Execute_RRC_E'Access;
      Table (16#0C#) := Definitions.Execute_RRC_H'Access;
      Table (16#0D#) := Definitions.Execute_RRC_L'Access;
      Table (16#0E#) := Definitions.Execute_RRC_Addr_HL'Access;
      Table (16#0F#) := Definitions.Execute_RRC_A'Access;
      Table (16#10#) := Definitions.Execute_RL_B'Access;
      Table (16#11#) := Definitions.Execute_RL_C'Access;
      Table (16#12#) := Definitions.Execute_RL_D'Access;
      Table (16#13#) := Definitions.Execute_RL_E'Access;
      Table (16#14#) := Definitions.Execute_RL_H'Access;
      Table (16#15#) := Definitions.Execute_RL_L'Access;
      Table (16#16#) := Definitions.Execute_RL_Addr_HL'Access;
      Table (16#17#) := Definitions.Execute_RL_A'Access;
      Table (16#18#) := Definitions.Execute_RR_B'Access;
      Table (16#19#) := Definitions.Execute_RR_C'Access;
      Table (16#1A#) := Definitions.Execute_RR_D'Access;
      Table (16#1B#) := Definitions.Execute_RR_E'Access;
      Table (16#1C#) := Definitions.Execute_RR_H'Access;
      Table (16#1D#) := Definitions.Execute_RR_L'Access;
      Table (16#1E#) := Definitions.Execute_RR_Addr_HL'Access;
      Table (16#1F#) := Definitions.Execute_RR_A'Access;
      Table (16#20#) := Definitions.Execute_SLA_B'Access;
      Table (16#21#) := Definitions.Execute_SLA_C'Access;
      Table (16#22#) := Definitions.Execute_SLA_D'Access;
      Table (16#23#) := Definitions.Execute_SLA_E'Access;
      Table (16#24#) := Definitions.Execute_SLA_H'Access;
      Table (16#25#) := Definitions.Execute_SLA_L'Access;
      Table (16#26#) := Definitions.Execute_SLA_Addr_HL'Access;
      Table (16#27#) := Definitions.Execute_SLA_A'Access;
      Table (16#28#) := Definitions.Execute_SRA_B'Access;
      Table (16#29#) := Definitions.Execute_SRA_C'Access;
      Table (16#2A#) := Definitions.Execute_SRA_D'Access;
      Table (16#2B#) := Definitions.Execute_SRA_E'Access;
      Table (16#2C#) := Definitions.Execute_SRA_H'Access;
      Table (16#2D#) := Definitions.Execute_SRA_L'Access;
      Table (16#2E#) := Definitions.Execute_SRA_Addr_HL'Access;
      Table (16#2F#) := Definitions.Execute_SRA_A'Access;
      Table (16#30#) := Definitions.Execute_SWAP_B'Access;
      Table (16#31#) := Definitions.Execute_SWAP_C'Access;
      Table (16#32#) := Definitions.Execute_SWAP_D'Access;
      Table (16#33#) := Definitions.Execute_SWAP_E'Access;
      Table (16#34#) := Definitions.Execute_SWAP_H'Access;
      Table (16#35#) := Definitions.Execute_SWAP_L'Access;
      Table (16#36#) := Definitions.Execute_SWAP_Addr_HL'Access;
      Table (16#37#) := Definitions.Execute_SWAP_A'Access;
      Table (16#38#) := Definitions.Execute_SRL_B'Access;
      Table (16#39#) := Definitions.Execute_SRL_C'Access;
      Table (16#3A#) := Definitions.Execute_SRL_D'Access;
      Table (16#3B#) := Definitions.Execute_SRL_E'Access;
      Table (16#3C#) := Definitions.Execute_SRL_H'Access;
      Table (16#3D#) := Definitions.Execute_SRL_L'Access;
      Table (16#3E#) := Definitions.Execute_SRL_Addr_HL'Access;
      Table (16#3F#) := Definitions.Execute_SRL_A'Access;
      return Table;
   end Build_CB_Table;

   Main_Table : constant Handler_Table := Build_Main_Table;
   CB_Table   : constant Handler_Table := Build_CB_Table;

   function Main_Handler
     (Opcode : Byte) return Instruction_Handler is
   begin
      return Main_Table (Opcode);
   end Main_Handler;

   function CB_Handler
     (Opcode : Byte) return Instruction_Handler is
   begin
      return CB_Table (Opcode);
   end CB_Handler;

end Gade.Dev.CPU.Generic_Dispatch_Prototype;
