name: Generate gnatformat bundle

on:
  workflow_dispatch:

env:
  GNATFORMAT_BUNDLE_ARTIFACT: gnatformat-bundle-ubuntu
  GNATFORMAT_BUNDLE_ARCHIVE: gnatformat-ubuntu.tar.zst

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shared CI setup
        uses: ./.github/actions/ci-setup

      - name: Install gnatformat
        run: alr install gnatformat

      - name: Create bundle archive
        shell: sh
        run: |
          set -eu
          tar --zstd -cf "${RUNNER_TEMP}/${GNATFORMAT_BUNDLE_ARCHIVE}" -C "${HOME}" .alire

      - name: Upload gnatformat bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GNATFORMAT_BUNDLE_ARTIFACT }}
          path: ${{ runner.temp }}/${{ env.GNATFORMAT_BUNDLE_ARCHIVE }}
          compression-level: 0
          retention-days: 90
